observe_entities:
  -
    type: appinstance
    level: PROCESS
    keys:
      - pgid
      - machine_id
    labels:
      - processes
  -
    type: pod
    level: PROCESS
    keys:
      - pod_id
      - machine_id
    labels:
      - pod
