topo_relations:
  -
    type: host
    dependingitems:
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: machine_id
                to: uuid
            requires:
              -
                side: from
                label: host_type
                value: vm
              -
                side: to
                label: comm
                value: qemu-kvm
      -
        id: has_vhost
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: machine_id
                to: uuid
            requires:
              -
                side: from
                label: host_type
                value: vm
            likes:
              -
                side: to
                label: comm
                value: vhost
  -
    type: container
    dependingitems:
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: proc
          -
            type: container
          -
            type: pod
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
            requires:
              -
                side: from
                label: pod_id
                value: null
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: pod
            matches:
              -
                from: pod_id
                to: pod_id
              -
                from: machine_id
                to: machine_id
  -
    type: pod
    dependingitems:
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: proc
          -
            type: container
          -
            type: pod
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: proc
    dependingitems:
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
            requires:
              -
                side: from
                label: container_id
                value: null
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: appinstance
            matches:
              -
                from: pgid
                to: pgid
              -
                from: machine_id
                to: machine_id
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: container
            matches:
              -
                from: container_id
                to: container_id
              -
                from: machine_id
                to: machine_id
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: proc
          -
            type: container
          -
            type: pod
      -
        id: has_vhost
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: uuid
                to: uuid
            requires:
              -
                side: from
                label: comm
                value: qemu-kvm
            likes:
              -
                side: to
                label: comm
                value: vhost
  -
    type: thread
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: endpoint
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: tcp_link
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
      -
        id: is_peer
        layer: direct
        toTypes:
          -
            type: tcp_link
            matches:
              -
                from: server_ip
                to: server_ip
              -
                from: server_port
                to: server_port
              -
                from: client_ip
                to: client_ip
            requires:
              -
                side: from
                label: role
                value: client
              -
                side: to
                label: role
                value: server
  -
    type: sli
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: cpu
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: nic
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: disk
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: block
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: disk
            matches:
              -
                from: disk_name
                to: disk_name
              -
                from: machine_id
                to: machine_id
  -
    type: fs
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: qdisc
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: nic
            matches:
              -
                from: dev_name
                to: dev_name
              -
                from: machine_id
                to: machine_id
  -
    type: net
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: mem
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
